# Generated by Django 3.2 on 2021-06-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
